export class ColorKeys {
  static readonly DISABLED = "disabled_color"
  static readonly VIEW = "view_color"
  static readonly TEXT_PRIMARY = "text_primary_color"
  static readonly TEXT_SECONDARY = "text_secondary_color"
  static readonly TEXT_PLACEHOLDER = "text_placeholder_color"
  static readonly SUCCESS = "success_color"
  static readonly DANGER = "danger_color"
  static readonly WARNING = "warning_color"
}